### PR TITLE
sync up with kubeflow/manifests

### PR DESCRIPTION
**Pull request by yhwang**
sync up with kubeflow/manifests. this includes the kserve and its web-app

### CODE REVIEW

**Comment by yhwang** [comment]
verified on IKS 1.21. e2e sample works well.
one thing that needs to be updated on IKS overlays is:
kserve is deployed as standalone because, in kubeflow v1.5, kfserving is the default one. I will create overlays to make kserve as the default.

**Comment by yhwang** [comment]
cc @Tomcli

**Comment by Tomcli** [comment]
Hey @yhwang, sorry I have some difficulty to rebase your branch to sync with `main` branch. Can you rebase it one more time?

**Comment by yhwang** [comment]
should be good now

**Comment by yhwang** [comment]
wait...

**Comment by yhwang** [comment]
I see. you already merged kserve changes into main branch. let me close this PR.

**Pull request closed without merging**
